# backend:
#   name: git-gateway
#   branch: main

# media_folder: "public/images"
# public_folder: "/images"

# collections:
#   - name: "posts"
#     label: "Blog Posts"
#     folder: "content/posts"
#     create: true
#     slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
#     fields:
#       - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
#       - {label: "Title", name: "title", widget: "string"}
#       - {label: "Publish Date", name: "date", widget: "datetime"}
#       - {label: "Body", name: "body", widget: "markdown"}

backend:
  name: github
  repo: mykytan-byte/decap-auth0
  branch: main
  base_url: https://decap-auth0.pages.dev
  auth_endpoint: /auth

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

# Enable PKCE fields (optional, recommended)
auth:
  email_claim: email
  first_name_claim: first_name
  last_name_claim: last_name
  avatar_url_claim: avatar_url

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in Decap CMS (optional)
site_url: https://effulgent-pony-3f4e2d.netlify.app
